services:
  dms_rest_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - dms_network

  webui:
    image: dms_webui
    build:
      context: ./DMS_WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - dms_rest_api
    networks:
      - dms_network

networks:
  dms_network:
    driver: bridge
