version: '3.8'

services:
  dms_rest_api:
    image: dms_rest_api
    build:
      context: ./DMS_REST_API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  webui:
    image: dms_webui
    build:
      context: ./DMS_WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DMS_WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./DMS_WebUI/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - dms_rest_api
