services:
  dms:
    image: dms
    build:
      context: .
      dockerfile: DMS/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
