version: '3.8'

services:
  dms_rest_api:
    image: dms_rest_api
    build:
      context: .
      dockerfile: /DMS_REST_API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - dms_dal
      - rabbitmq
    restart: unless-stopped

  webui:
    image: dms_webui
    build:
      context: ./DMS_WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DMS_WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./DMS_WebUI/wwwroot:/usr/share/nginx/html     # Statische Dateien korrekt mounten
    depends_on:
      - dms_rest_api
 

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data

  dms_dal:
    image: dms_dal
    build:
      context: .
      dockerfile: ./DMS_DAL/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - db
  
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ocr_worker:
      build:
        context: .
        dockerfile: DMS_OCR/Dockerfile
      depends_on:
        rabbitmq:
          condition: service_healthy
      environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USER=guest
        - RABBITMQ_PASSWORD=guest

volumes:
    postgres_data:
    
    
