services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DMS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dms-network

  dms_rest_api:
    image: dms_rest_api
    build:
      context: ./DMS_REST_API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=DMS;Username=postgres;Password=123
    depends_on:
      - db
    networks:
      - dms-network

  webui:
    image: dms_webui
    build:
      context: ./DMS_WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DMS_WebUI/nginx.conf:/etc/nginx/nginx.conf
      - ./DMS_WebUI/wwwroot:/app/wwwroot
    depends_on:
      - dms_rest_api
    networks:
      - dms-network

networks:
  dms-network:

volumes:
  postgres_data:
