version: '3.8'

services:
  dms_rest_api:
    image: dms_rest_api
    build:
      context: .
      dockerfile: /DMS_REST_API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - dms_dal

  webui:
    image: dms_webui
    build:
      context: ./DMS_WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DMS_WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./DMS_WebUI/wwwroot:/usr/share/nginx/html     # Statische Dateien korrekt mounten
    depends_on:
      - dms_rest_api
 

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data

  dms_dal:
    image: dms_dal
    build:
      context: .
      dockerfile: ./DMS_DAL/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - db

volumes:
    postgres_data:
